### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by gaby** [sphqxe/NATS-WebUI#57]
Hello @sphqxe do you have any plans to continue developing this project, or would you rather someone else take over in a new fork or maybe transferring this repo?

Thanks!

**Comment by gaby** [comment]
@sphqxe Friendly ping 👋 I noticed you were recently active on Github. Would you consider transferring this repo so that work can continue?

Thanks!

**Comment by sphqxe** [comment]
Please go ahead with forking it.

**Comment by gaby** [comment]
@sphqxe Thanks for the reply! Is transferring the repo not an option? It would help keep the history, issues, and watchers. With a fork all that would be lost.

Instructions here: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account
